print("please enter your Bio-Data:\n")
name=input("please enter your name:")
age=input("please enter your age:")
phno=input("please enter your phno:")
address=input("please enter your address:")
print(type(name))
print(type(age))
print(type(phno))
print(type(address))
print(int(age))
print(int(phno))
print(name,age,phno,address)

